logging:
    file:
        name: ../logs/web.log
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true
    global-config:
        db-config:
            update-strategy: ignored
    mapper-locations: classpath*:/mapper/*.xml
server:
    port: 7072
    servlet:
        context-path: /web
spring:
    mvc:
        static-path-pattern: /images/**
    application:
        name: bbs-web
    datasource:
        #driver-class-name: org.sqlite.JDBC
        #url: jdbc:sqlite:./bbsServer/bbs.db
        #username: root
        #password: root
        username: BBS
        password: 233333
        url: jdbc:oracle:thin:@localhost:1521:xe
        driver-class-name: oracle.jdbc.OracleDriver

    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 20MB

file:
    image:
        path: ./bbsServer/bbs-web/src/main/resources/static/
        tpath: ./bbsServer/bbs-web/target/classes/static/
