logging:
    file:
        name: ../logs/admin.log
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true #驼峰映射
    global-config:
        db-config:
            update-strategy: ignored
    mapper-locations: classpath*:/mapper/*.xml
server:
    port: 7071
    servlet:
        context-path: /admin
spring:
    application:
        name: bbs-admin
    datasource:
        username: BBS
        password: 233333
        url: jdbc:oracle:thin:@localhost:1521:orcl
        driver-class-name: oracle.jdbc.OracleDriver
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 20MB
file:
    image:
        path: ./bbsServer/bbs-web/src/main/resources/static/
        tpath: ./bbsServer/bbs-web/target/classes/static/