logging:
    file:
        name: ../logs/admin.log
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true #驼峰映射
    global-config:
        db-config:
            update-strategy: ignored
    mapper-locations: classpath*:/mapper/*.xml
server:
    port: 7071
    servlet:
        context-path: /admin
spring:
    application:
        name: bbs-admin
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: qq2712448668
        url: jdbc:mysql://localhost:3306/bbs
        username: root
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 20MB
file:
    image:
        path: ./bbs-web/src/main/resources/static/
        tpath: ./bbs-web/target/classes/static/